/**
 * Curated lexicon of constructs common in academic literature (social sciences,
 * education, management, information systems). Used by the local rule-based AI
 * provider as a recall aid — surface forms found in the paper are always kept,
 * never invented ones.
 */
export const CONSTRUCT_LEXICON = [
  'job satisfaction',
  'employee satisfaction',
  'work satisfaction',
  'user satisfaction',
  'customer satisfaction',
  'organizational commitment',
  'affective commitment',
  'continuance commitment',
  'normative commitment',
  'turnover intention',
  'turnover intent',
  'intent to leave',
  'intention to leave',
  'attrition intention',
  'job performance',
  'task performance',
  'employee performance',
  'work performance',
  'organizational citizenship behavior',
  'counterproductive work behavior',
  'person-organization fit',
  'person-job fit',
  'work-life balance',
  'work-family conflict',
  'employee engagement',
  'work engagement',
  'job involvement',
  'perceived organizational support',
  'leader-member exchange',
  'transformational leadership',
  'authentic leadership',
  'servant leadership',
  'burnout',
  'emotional exhaustion',
  'job stress',
  'work stress',
  'job insecurity',
  'job autonomy',
  'psychological empowerment',
  'employee empowerment',
  'intrinsic motivation',
  'extrinsic motivation',
  'self-efficacy',
  'computer self-efficacy',
  'creative self-efficacy',
  'collective efficacy',
  'teacher efficacy',
  'knowledge sharing',
  'knowledge hiding',
  'knowledge management',
  'digital literacy',
  'digital competence',
  'technological competence',
  'perceived usefulness',
  'perceived ease of use',
  'technology acceptance',
  'technology readiness',
  'organizational justice',
  'procedural justice',
  'distributive justice',
  'interactional justice',
  'trust in management',
  'trust in teacher',
  'team cohesion',
  'team effectiveness',
  'innovation behavior',
  'innovative behavior',
  'entrepreneurial intention',
  'career satisfaction',
  'career self-efficacy',
  'job embeddedness',
  'organizational identification',
  'subjective well-being',
  'subjective well being',
  'psychological well-being',
  'life satisfaction',
  'emotional labor',
  'psychological capital',
  'workplace resilience',
  'mindfulness',
  'critical thinking',
  'self-regulated learning',
  'academic achievement',
  'student engagement',
  'learning outcomes',
  'parental involvement',
  'social support',
  'collective intelligence',
  'team trust',
  'information security awareness',
  'privacy concern',
  'smartphone addiction',
  'social media use',
  'online learning behavior',
  'task-technology fit',
];

/** Names that would create useless constructs if captured from a definition cue. */
export const GENERIC_NAMES = new Set([
  'construct',
  'variable',
  'concept',
  'term',
  'theory',
  'model',
  'study',
  'paper',
  'scale',
  'index',
  'measure',
  'measurement',
  'instrument',
  'factor',
  'effect',
  'relationship',
  'association',
  'difference',
  'group',
  'condition',
  'item',
  'question',
  'statement',
  'analysis',
  'sample',
  'participant',
  'respondent',
  'result',
  'finding',
  'hypothesis',
  'prior work',
  'prior study',
  'this study',
  'the present study',
  'the authors',
  'one another',
  'each other',
]);

/**
 * Groups of terms that mean the same thing under different names (jangle risk).
 * Compared in normalized form (see normalizeName).
 */
export const SYNONYM_GROUPS = [
  ['job satisfaction', 'employee satisfaction', 'work satisfaction', 'satisfaction with work'],
  ['turnover intention', 'turnover intent', 'intent to leave', 'intention to leave', 'attrition intention'],
  ['organizational commitment', 'organisational commitment', 'commitment to the organization'],
  ['organizational citizenship behavior', 'ocb', 'citizenship behavior'],
  ['person-organization fit', 'person organisation fit', 'p-o fit'],
  ['work-life balance', 'work life balance', 'work family balance'],
  ['self-efficacy', 'self efficacy'],
  ['digital literacy', 'digital competence'],
  ['knowledge sharing', 'knowledge exchange'],
  ['job performance', 'employee performance', 'work performance', 'task performance'],
  ['perceived usefulness', 'usefulness'],
  ['perceived ease of use', 'ease of use'],
  ['subjective well-being', 'subjective well being', 'subjective wellbeing'],
  ['emotional exhaustion', 'emotional depletion'],
  ['student engagement', 'learner engagement'],
];

const synonymIndex = new Map();
SYNONYM_GROUPS.forEach((group, i) => {
  for (const term of group) synonymIndex.set(term, i);
});

/** True when two normalized names belong to the same synonym group. */
export function areSynonyms(a, b) {
  const ia = synonymIndex.get(a);
  const ib = synonymIndex.get(b);
  return ia !== undefined && ia === ib;
}
